# Generated by Django 5.0.6 on 2024-06-27 13:28

import django.db.models.deletion
import upload_validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=20, verbose_name='Field Type')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(verbose_name='FCM Token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fcmtoken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
                ('token', models.ManyToManyField(related_name='fcm_token', to='exizprint.notificationtoken')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('done', 'done'), ('cancel', 'cancel')], null=True, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('key', models.CharField(max_length=30, verbose_name='Key')),
                ('value', models.CharField(max_length=30, verbose_name='Value')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exizprint.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Service Name')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('image', models.ImageField(default='ProfileImages/download.jpeg', upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exizprint.services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_of', to='exizprint.services'),
        ),
        migrations.CreateModel(
            name='FormFieldName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('field_name', models.CharField(max_length=20, null=True, verbose_name='Field')),
                ('value', models.CharField(blank=True, null=True, verbose_name='values if needed')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='field_type_of', to='exizprint.formfieldtype')),
                ('Service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='field', to='exizprint.services')),
            ],
        ),
    ]
