# Generated by Django 5.0.6 on 2024-08-19 09:29

import django.db.models.deletion
import gdstorage.storage
import phonenumber_field.modelfields
import upload_validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TempFileField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_file', models.FileField(blank=True, null=True, upload_to='Temp/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.pdf'], allowed_types=['application/pdf', 'image/jpg', 'image/jpeg', 'image/png'])], verbose_name='Temp File')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('pin_code', models.IntegerField(verbose_name='Pin Code')),
                ('house_number', models.CharField(max_length=100, verbose_name='House Number')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Phone Number')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(verbose_name='FCM Token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcmtoken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noti_of', to=settings.AUTH_USER_MODEL)),
                ('token', models.ManyToManyField(related_name='fcm_token', to='exizprint.notificationtoken')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('bill', models.FloatField(verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('status', models.CharField(blank=True, choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('pending', 'pending'), ('in_progress', 'in_progress'), ('done', 'done'), ('cancelled', 'cancelled')], default='unpaid', null=True, verbose_name='Status')),
                ('checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exizprint.checkout')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('key', models.CharField(verbose_name='Key')),
                ('value', models.CharField(verbose_name='Value')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exizprint.orders')),
            ],
        ),
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=200, verbose_name='Field Name')),
                ('file', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['WRITER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'exizprint@vaulted-night-428015-c9.iam.gserviceaccount.com'),)), upload_to='', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.pdf'], allowed_types=['application/pdf', 'image/jpg', 'image/jpeg', 'image/png'])], verbose_name='File')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exizprint.orders')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=100)),
                ('ordr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exizprint.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Service Name')),
                ('desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('image', models.ImageField(default='ProfileImages/download.jpeg', upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exizprint.services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('above', models.FloatField(blank=True, null=True, verbose_name='Above Quantity')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Rate Per Pcs.')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='exizprint.services')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_of', to='exizprint.services'),
        ),
        migrations.CreateModel(
            name='FormFieldName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('field_name', models.CharField(max_length=20, null=True, verbose_name='Field')),
                ('value', models.CharField(blank=True, null=True, verbose_name='values if needed')),
                ('field_type', models.CharField(choices=[('txt', 'Text'), ('ch', 'Choices'), ('int', 'Number'), ('file', 'File')], verbose_name='FormFieldType')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to='exizprint.services')),
            ],
        ),
    ]
