# Generated by Django 5.0.6 on 2024-07-06 17:25

import gdstorage.storage
import upload_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempFileField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_file', models.FileField(blank=True, null=True, upload_to='Temp/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.pdf'], allowed_types=['application/pdf', 'image/jpg', 'image/jpeg', 'image/png'])], verbose_name='Temp File')),
            ],
        ),
        migrations.AlterField(
            model_name='filefield',
            name='file',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(permissions=(gdstorage.storage.GoogleDriveFilePermission(gdstorage.storage.GoogleDrivePermissionRole['WRITER'], gdstorage.storage.GoogleDrivePermissionType['USER'], 'exizprint@vaulted-night-428015-c9.iam.gserviceaccount.com'),)), upload_to='', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.png', '.jpg', '.jpeg', '.pdf'], allowed_types=['application/pdf', 'image/jpg', 'image/jpeg', 'image/png'])], verbose_name='File'),
        ),
    ]
