# Generated by Django 5.0.6 on 2024-06-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exizprint.services'),
        ),
    ]
