# Generated by Django 5.0.6 on 2024-06-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
