# Generated by Django 5.0.6 on 2024-06-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0003_remove_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fcm_token', to='exizprint.notificationtoken'),
        ),
    ]
