# Generated by Django 5.0.6 on 2024-06-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0003_alter_services_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Field Type')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exizprint.services')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20, null=True, verbose_name='Field')),
                ('value', models.CharField(blank=True, null=True, verbose_name='values if needed')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exizprint.formfieldtype')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exizprint.serviceform')),
            ],
        ),
    ]
