# Generated by Django 5.0.6 on 2024-06-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0004_formfieldtype_services_desc_serviceform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldname',
            name='form',
        ),
        migrations.AddField(
            model_name='formfieldname',
            name='Service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='exizprint.services'),
        ),
        migrations.DeleteModel(
            name='ServiceForm',
        ),
    ]
