# Generated by Django 5.0.6 on 2024-06-26 10:38

import upload_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0004_alter_notification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image'),
        ),
    ]
