# Generated by Django 5.0.6 on 2024-06-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0005_remove_formfieldname_form_formfieldname_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exizprint.services')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='Key')),
                ('value', models.CharField(max_length=30, verbose_name='Value')),
                ('modelOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exizprint.orders')),
            ],
        ),
    ]
