# Generated by Django 5.0.6 on 2024-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0008_alter_notificationtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='token',
        ),
        migrations.AddField(
            model_name='notification',
            name='token',
            field=models.ManyToManyField(related_name='fcm_token', to='exizprint.notificationtoken'),
        ),
    ]
