# Generated by Django 5.0.6 on 2024-06-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0009_remove_notification_token_notification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtoken',
            name='token',
            field=models.CharField(verbose_name='FCM Token'),
        ),
    ]
