# Generated by Django 5.0.6 on 2024-06-26 19:42

import upload_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exizprint', '0010_alter_notificationtoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ServiceImage/', validators=[upload_validator.FileTypeValidator(allowed_types=['image/*'])], verbose_name='Image')),
            ],
        ),
    ]
