# Generated by Django 5.0.6 on 2024-07-15 16:34

import datetime
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 16, 39, 6, 168406, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 16, 49, 6, 167899, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=22043, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='9623d66dd7c3f509b78fa36e3349803168c9e5c4273c23283a4daa5ca355', verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default='1550063f6eacfdefa953013e8733a05f1650', help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, validators=[django_otp.util.hex_validator], verbose_name='Secret Key'),
        ),
    ]
