# Generated by Django 5.0.6 on 2024-07-15 16:34

import datetime
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 16, 39, 13, 913835, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 15, 16, 49, 13, 913300, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=74450, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='b58ecb859c1a212d39f6bfdbff13ded99773047c6367707df3671220490f', verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default='a6640d21e2e61bc00f71f4e3b5d1', help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, validators=[django_otp.util.hex_validator], verbose_name='Secret Key'),
        ),
    ]
