# Generated by Django 5.0.6 on 2024-06-13 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 9, 58, 0, 212430, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 8, 0, 211486, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=57423, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='3aff85e393cb6c14af59ee5138e50b3c0d2287cb783c8e4070b7', verbose_name='Salt'),
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
