# Generated by Django 5.0.6 on 2024-06-26 09:55

import datetime
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 10, 0, 37, 789550, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 10, 10, 37, 788847, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=54688, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='78054e02d408365ebaafb84d70e8c593368fb1a167c7193565cfe0df', verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default='36b124403cb0e6f6aeb96927a2', help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, unique=True, validators=[django_otp.util.hex_validator], verbose_name='Secret Key'),
        ),
    ]
