# Generated by Django 5.0.6 on 2024-06-13 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profileimage_profile_remove_userprofile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 40, 4, 633381, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 50, 4, 632429, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=14614, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='fd4390aa3ae298bd81ef42c808feba6e501f893da60ea3a751', verbose_name='Salt'),
        ),
    ]
