# Generated by Django 5.0.6 on 2024-06-13 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 10, 55, 27, 840967, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 11, 5, 27, 840017, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=46230, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='96e18d592c6e0514d35bdf93ab757a87b032372b4be4910b4b3a968f8ec4', verbose_name='Salt'),
        ),
    ]
