# Generated by Django 5.0.6 on 2024-06-26 13:28

import datetime
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 13, 33, 11, 368816, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 13, 43, 11, 368048, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=15780, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='8d687d0bc846bfa8debcd94796ffc2407beca811d1e94165eaeddfcb85', verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default='0b0b2d07da5adbda06e8b0500b5fd178e0de', help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, unique=True, validators=[django_otp.util.hex_validator], verbose_name='Secret Key'),
        ),
    ]
