# Generated by Django 5.0.6 on 2024-06-26 15:31

import datetime
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 15, 36, 14, 7867, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 15, 46, 14, 7034, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=43692, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='31183ba324d0400731e73cc2bca30646c08faf4aac65f21420a404f4', verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default='686278636c8e330ec6e0', help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, unique=True, validators=[django_otp.util.hex_validator], verbose_name='Secret Key'),
        ),
    ]
