# Generated by Django 5.0.6 on 2024-06-26 19:42

import datetime
import django_otp.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_otptoken_expiry_alter_passresettoken_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 19, 47, 31, 992169, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='passresettoken',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 19, 57, 31, 991499, tzinfo=datetime.timezone.utc), verbose_name='Expiry'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='nonce',
            field=models.CharField(default=66701, verbose_name='Nonce'),
        ),
        migrations.AlterField(
            model_name='salt',
            name='salt',
            field=models.CharField(default='6449404890b356328cafab357df4f762755c482d5d955a2881', verbose_name='Salt'),
        ),
        migrations.AlterField(
            model_name='verificationdevice',
            name='secret_key',
            field=models.CharField(default='8c45fc44a8b39d462f410d8b6131', help_text='Hex-encoded secret key to generate totp tokens.', max_length=40, unique=True, validators=[django_otp.util.hex_validator], verbose_name='Secret Key'),
        ),
    ]
